apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # Dataviz métier (dashboard business séparé du dashboard observabilité)
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: audit_immo_energie_44
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: false
